### ISSUE TITLE
auto-rename doesn't work for duplicates

### ISSUE THREAD

**Issue by FinnYoung** [gibaBR/Switch-Backup-Manager#10]
I tried to use context menu on a title and 'tools -> auto-rename -> all'. Both do not work.
File name: bbb-h-adz6b.xci
Release from: BigBlueBox

**Comment by gibaBR** [comment]
Can you try it with the lastest version?

**Comment by FinnYoung** [comment]
i tried. in a directory i have: `Thimbleweed Park.xci` and `bbb-h-adz6b.xci`
both are `0100AF2009B30000`
after importing directory i don't see "Thimbleweed Park" at all :\
looks like application just skipped this title

**Comment by gibaBR** [comment]
It's the way the application is designed. It uses Title ID as a key, so you cannot have two files with the same tittle ID on the same category (local files, sd card, etc). Why would you want it anyway?

**Comment by gibaBR** [comment]
> i'm ok about listing some file just once, but if folder contains duplicates nothing was added to library at all (at least at release i tried). which is wrong.

Yes, it is wrong and should not happen. When I try to reproduce it on tha lastest version I got this on my log:
_2018-08-02 18:52:49.202 [WARNING] File Tiny Barbarian DX [0100D940022F6000] [v].xci already exists at destination path. Ignoring this file!
2018-08-02 18:52:49.240 [INFO]    Finished autorename local files._

That is what I expect to happen. Could you try that on the last release?
About having a .xci and .nsp with the same title ID, it would not be a problem as it is stored on different databases.


> what prevents you having this functionality to change scan to use some file utils and go through files in directory getting some additional info and build a library using file names as a keys

Because, in my opinion, that would not be reliable. 


Thank you for helping me make a better software.

**Comment by FinnYoung** [comment]
i'll be able to check it only 6+ hours later. and will recheck scaling issue. i've not updated for a while

> Thank you for helping me make a better software.

you are welcome. and sorry for being a pain in the neck :D
