### ISSUE TITLE
[REQUEST] add NSZ compressed format support

### ISSUE THREAD

**Issue by bartvincke** [gibaBR/Switch-Backup-Manager#152]
currently, v1.2.2 does not recognize the new compressed format, please add this format as well

**Comment by garoxas** [comment]
hey @gibaBR someone just reported that apparently NSZ format only compress program NCA which is not used by SBM, so a simple changes to allow .nsz extension will do as can be seen in the screenshot below

![sbm](https://user-images.githubusercontent.com/11901820/67219523-67f33b00-f452-11e9-8817-58ef7d952e51.png)

but please do mind there might be some issues I missed during testing
I've tested with several files and looks like everything run normal, but we'll never know. the format itself is still in infancy so there could be some few changes later on that may break the compatibility. hell if someone decided to compress all NCA then it'll break the compatibility since I didn't (and won't) add support for NCZ

so what do you think about it? if you're okay with it, I'm ready with a PR

**Comment by gibaBR** [comment]
As always, you are the man!!

Do it! Thank you very much, one more time.

[]`s
---
Gilberto Júnior
http://raspberrybrasil.blogspot.com.br/
http://www.flickr.com/photos/gibajr/

**Comment by garoxas** [comment]
You're very much welcome man 😄
