### ISSUE TITLE
SD card XCI's not being displayed

### ISSUE THREAD

**Issue by karl0ss** [gibaBR/Switch-Backup-Manager#19]
Using the working version you sent me via Mega, network scanning is working fine..

I have plugged in my sdcard and pointed it at the correct drive, xci's were scanned, but nothing added to the list, but total shows "21 Total (115.86 GB)

Nothing added to the log file to attach to this ticket.

**Comment by gibaBR** [comment]
Please take a look at the config window, maybe the option to scan xci files is not checked.

**Comment by G-ferrari** [comment]
@gibaBR  I have the same issue. 
Im in version 1.2.0 - dowloaded yesterday. 

The program sees my SDCard, he can count and transfer the games from PC to SD, but the games does not show.

Thank you for the great app man. This is awesome. 
PS: Are you from brazil?! - Cause I am

**Comment by gibaBR** [comment]
Yes. Sou sim.

Em 20 de nov de 2018 14:41, "G-ferrari" <notifications@github.com> escreveu:

@gibaBR <https://github.com/gibaBR> I have the same issue.
Im in version 1.2.0 - dowloaded yesterday.

The program sees my SDCard, he can count and transfer the games from PC to
SD, but the games does not show.

Thank you for the great app man. This is awesome.
PS: Are you from brazil?! - Cause I am

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/gibaBR/Switch-Backup-Manager/issues/19#issuecomment-440365221>,
or mute the thread

**Comment by G-ferrari** [comment]
Poxa, que fera cara! 
Parabéns pelo seu trabalho ai. 

Então, to com problema q o programa acha meu SD mas ele nao mostra a lista dos jogos dentro. 
Ele sabe quantos GB tem faltando mas nao diz quanto ta ocupado (fica como 0mb na parte de baixo).

mas consigo usar o software pra passar do PC pro SD tranquilamente. Ja dei o check nas configurações internas mas ele continua não aparecendo, tem ideia do q seja?
