### ISSUE TITLE
Cant Open SBM on version 1.1.9 (Internal)

### ISSUE THREAD

**Issue by gibaBR** [gibaBR/Switch-Backup-Manager#75]
@garoxas There is something wrong. The program is not openning.

[SBM Fails.zip](https://github.com/gibaBR/Switch-Backup-Manager/files/2476406/SBM.Fails.zip)

**Comment by garoxas** [comment]
can you try this #76 

do you have function to update the xml without saving every time?
as you can see in FrmMain.backgroundWorkerUpdateVersionList_DoWork I'm doing lots of Util.UpdateXMLFromFileData call and I believe that flush the changes to the disk every single time, so that's why it's slow
if you have better alternative, please feel free to modify the code
thank you

**Comment by garoxas** [comment]
#77 
here's my new PR. please check and let me know if there's any issue
already tried with your XML files and I have no issue with that
